export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR = 'AJAX_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REDIRECTED = 'REDIRECTED';

export const GET_DRESS_SUCCESS = 'GET_DRESS_SUCCESS';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';