export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REDIRECTED = 'REDIRECTED';

export const GET_DRESS_SUCCESS = 'GET_DRESS_SUCCESS';
export const LIKE_DRESS_SUCCESS = 'LIKE_DRESS_SUCCESS';
export const DISLIKE_DRESS_SUCCESS = 'DISLIKE_DRESS_SUCCESS';
export const SORT_DRESS_SUCCESS = 'SORT_DRESS_SUCCESS';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';

export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';